Importing Necessary Libraries:

In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import datasets

## Loading the Dataset:

In [2]:
iris = datasets.load_iris()

## Visualizing the Dataset:

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [12]:
print(iris.data[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [13]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


#### Creating a DataFrame of the given Iris Data:

In [14]:
"""Creating a DataFrame of a given Iris Dataset"""
df = pd.DataFrame({
    'sepal length': iris.data[:,0],
    'sepal_width' : iris.data[:,1],
    'petal length': iris.data[:,2],
    'petal width' : iris.data[:,3],
    'species': iris.target
})

df.head()

petal length  petal width  sepal length  sepal_width  species
0           1.4          0.2           5.1          3.5        0
1           1.4          0.2           4.9          3.0        0
2           1.3          0.2           4.7          3.2        0
3           1.5          0.2           4.6          3.1        0
4           1.4          0.2           5.0          3.6        0